learning_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from polls.views import vote, IndexView, DetailView, ResultsView

#importante adicionar um namespace para diferenciar esse app de outros
app_name = 'polls'
urlpatterns = [
    #para view genericas
    path('',IndexView.as_view(), name='index'),
    #pk - pois será urilizado na  DetailView
    path('<int:pk>/', DetailView.as_view(), name='polls_detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='polls_results'),
    path('<int:question_id>/vote/', vote, name='polls_vote')
    #----- view mais descritiva
    # path('', index, name='index'),
    # path('<int:question_id>/', detail, name='polls_detail'),
    # path('<int:question_id>/results', result, name='polls_results'),
    # path('<int:question_id>/vote', vote, name='polls_vote')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    #data da publicação
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    # #method test
    def was_published_recently(self):
        return self.pub_date  <= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

#view retorna HttpResponse com o conteudo, ou Http404
from polls.models import Question, Choice

#usamos aqui a ListView e DetailView
#DetailView - espera o valor de chave primaria pegue pela URL(chamado de pk)

#para view genericas
class  IndexView(generic.ListView):
    #template_name para não auto gerar um nome
    template_name = 'polls/index.html'
    #quando quero informar o nome da minha variável que vou usar no template, informo aqui
    #se não informar o nome do meu model será o da variável,
    #exemplo modelo - Question. Var - question
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            #pub_date__lte - irá retornar cujo seja igual ou menor do timezone.now()
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class  DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class  ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        #request.POST - é um objeto que permite acessar os dados submetidos
        #request.POST['choice'] -  retorna o id da opçao selecionada
        #request.POST -  estamos utilizando request post para os dados só podem ser acessado por chamada POST
        #request.POST['choice'] levanta um KeyError caso não tenha um choice no POST assim será re-exibido
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        #isso para acrescentar um voto não é a melhor forma , pois se é preciso estudar - condição de concorrência
        #https://docs.djangoproject.com/pt-br/2.1/ref/models/expressions/#avoiding-race-conditions-using-f
        selected_choice.votes += 1
        selected_choice.save()
        #é uma boa prática depois de ter sucesso com POST retornar um HttpResponseRedirect
        #reverse - é uma funçar que ajuda a evitar  colocar url dentro da view
        return HttpResponseRedirect(reverse('polls:polls_results', args=(question_id,)))
#----- view mais descritiva
#
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     template =loader.get_template('polls/index.html')
#     # contexto é um dicionário mapeando nomes de variáveis ​​para objetos Python.
#     context ={
#         'latest_question_list': latest_question_list
#     }
#     #return HttpResponse(template.render(context,request))
#     return render(request, 'polls/index.html',context)
#
#     # # mostra as últimas 5 salva no banco
#     # latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # #return HttpResponse(latest_question_list)
#     # #separada por vírgulas, de acordo com sua data de publicação
#     # output = ', '.join([q.question_text for q in latest_question_list])
#     # return HttpResponse(output)
#
# def detail(request, question_id):
#     #dessa forma é melhor pois é a forma de não acoplar a camada de modelo
#     #com a camisada de visão
#     # existe - get_list_or_404()(utiliza filter) e o get_object_or_404()(utiliza get)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
#     #aqui estaria acoplando
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, 'polls/detail.html', {'question': question})
#
#
# def result(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html',{'question': question})
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         #request.POST - é um objeto que permite acessar os dados submetidos
#         #request.POST['choice'] -  retorna o id da opçao selecionada
#         #request.POST -  estamos utilizando request post para os dados só podem ser acessado por chamada POST
#         #request.POST['choice'] levanta um KeyError caso não tenha um choice no POST assim será re-exibido
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         #isso para acrescentar um voto não é a melhor forma , pois se é preciso estudar - condição de concorrência
#         #https://docs.djangoproject.com/pt-br/2.1/ref/models/expressions/#avoiding-race-conditions-using-f
#         selected_choice.votes += 1
#         selected_choice.save()
#         #é uma boa prática depois de ter sucesso com POST retornar um HttpResponseRedirect
#         #reverse - é uma funçar que ajuda a evitar  colocar url dentro da view
#         return HttpResponseRedirect(reverse('polls:polls_results', args=(question_id,)))

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>
        {{ question }}
    </h1>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form action="{% url 'polls:polls_vote' question.id %}" method="post">
        <!--trás uma segurança maior no form-->
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <!--como todo radio tem o mesmo nome , quando for enviado a opção escolhida irá vir com # e o nome-->
            <!--forloop.counter indica quantas vezes a tag for passou pelo o laço-->
            <input type="radio" name="choice" id="choice{{ forloop.counter}}" value="{{choice.id}}">
            <label for="choice{{ forloop.counter}}" >{{choice}}</label>
        <br>
        {%endfor%}
        <input type="submit" value="Vote">
    </form>
    <!--<ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
        {% endfor %}
    </ul>
-->
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>

    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list  %}
        <li>
            <!--<a href="{{question.id}}/">{{question.question_text}}</a>-->
            <!--polls_detail - isso é definido no arquivo urls-->
            <!--polls:polls_detail - 'polls:...' é o app_name na urls é feito para diferenciar dos outros apps-->
            <a href="{% url 'polls:polls_detail' question.id %}">{{ question.question_text}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available</p>
    {% endif %}

</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
    {% for choice in question.choice_set.all %}

        <li>{{ choice.choice_text}} -- {{choice.votes }} vote{{choice.votes|pluralize}}</li>
    {% endfor %}

    </ul>

    <a href="{% url 'polls:polls_detail' question.id %}">Vote again?</a>
</body>
</html>